#! /usr/bin/env python3
import sys, re, os

define = '''
Object.defineProperty(exports, "__esModule", {
    value: true
});
'''
require = r'\nvar (\w+) = require\(\'(.+)\'\);\n'
export = r'var (\w+) = exports.\1 ='

for jsfile in sys.argv[1:]:
    with open(jsfile) as file:
        text = file.read()

    header = '.pragma library\n'

    for qml in re.findall(r'/// QML (.+)\n', text):
        header += qml + '\n'

    for (name, filename) in re.findall(require, text):
    	header += '.import "{}.js" as QML{}\n'.format(filename, name)

    header += '\n'

    for (name, filename) in re.findall(require, text):
    	header += 'var {} = QML{}\n'.format(name, name)

    header += '\n'

    text = text.replace(define, '')
    text = re.sub(require, '', text)
    text = re.sub(r'exports.\w+ = \w+;\n', '', text)
    text = re.sub(export, r'var \1 =', text)

    text = header + text

    with open(jsfile, 'w') as file:
        file.write(text)
